// frontend/src/app/components/attention-card.component.ts
import {ChangeDetectionStrategy, Component, computed, input, output} from '@angular/core';
import {ButtonComponent} from '@lifekit-hq/ui';

import {type Attention} from '../api/devclaw.model';
import {AgoPipe} from '../shared/time';
import {DecideFormComponent} from './decide-form.component';

interface Option {
  text: string;
  firstLine: string;
  recommended: boolean;
}

/**
 * One goal's ask, the same on Needs you and on the goal page. Buttons exist only for a session
 * block: they are the session's options, the recommended one first. A host-authored stop shows
 * its fact, a free-text decide and cancel, never options the host made up.
 */
@Component({
  selector: 'dc-attention-card',
  imports: [AgoPipe, ButtonComponent, DecideFormComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let a = attention();
    @if (a.answered; as answered) {
      <p class="whitespace-pre-wrap text-cmn-sm text-text-primary">{{ a.question }}</p>
      <p class="mt-cmn-2 text-cmn-sm text-text-secondary">
        Answered {{ answered.madeAt | ago }}:
        <span class="text-text-primary">{{ answered.text }}</span>
        @if (answered.commentUrl) {
          ·
          <a
            [href]="answered.commentUrl"
            class="text-accent-default hover:underline"
            target="_blank"
            rel="noopener noreferrer"
            >thread</a
          >
        }
      </p>
      <p class="mt-cmn-1 font-mono text-cmn-xs text-text-secondary">
        waiting for the tick · {{ answered.waitingOn }}
      </p>
    } @else {
      <p class="mb-cmn-2 font-mono text-cmn-xs text-text-secondary">
        {{ a.kind }} · open {{ a.since | ago }}
        @if (a.link) {
          ·
          <a
            [href]="a.link"
            class="text-accent-default hover:underline"
            target="_blank"
            rel="noopener noreferrer"
            >{{ a.kind === 'session' || a.kind === 'env' ? 'issue' : 'thread' }}</a
          >
        }
      </p>
      <p class="whitespace-pre-wrap text-cmn-sm text-text-primary">{{ a.question }}</p>
      @if (a.kind === 'env') {
        <p class="mt-cmn-2 text-cmn-sm text-text-secondary">
          Wakes on its own once the credential probes green.
        </p>
      } @else {
        @if (options().length || takeDefault()) {
          <div
            class="mt-cmn-3 flex flex-wrap gap-cmn-2"
            role="group"
            aria-label="The session's options"
          >
            @for (option of options(); track $index) {
              <cmn-button
                [variant]="option.recommended ? 'primary' : 'secondary'"
                [disabled]="form.busy()"
                [attr.title]="option.text"
                (clicked)="form.decideWith(option.text)"
                size="sm"
              >
                {{ option.firstLine }}
                @if (option.recommended) {
                  <span class="font-mono text-cmn-xs opacity-75">recommended</span>
                }
              </cmn-button>
            }
            @if (takeDefault(); as fallback) {
              <cmn-button
                [disabled]="form.busy()"
                [attr.title]="fallback"
                (clicked)="form.decideWith(fallback)"
                size="sm"
              >
                take the default: {{ fallback }}
              </cmn-button>
            }
          </div>
        }
        <dc-decide-form
          #form
          [goalId]="goalId()"
          [placeholder]="
            options().length ? 'or answer in your own words' : 'your decision, posted on the issue'
          "
          [cancellable]="cancellable()"
          (decided)="decided.emit()"
          (cancelRequested)="cancelRequested.emit()"
          class="mt-cmn-3 block"
        />
      }
    }
  `,
})
export class AttentionCardComponent {
  public readonly goalId = input.required<string>();
  public readonly attention = input.required<Attention>();
  /** Offers Cancel goal next to Decide; the page owns the confirm. */
  public readonly cancellable = input(false);
  /** A decision was posted on the issue; the page re-reads its feed. */
  public readonly decided = output();
  public readonly cancelRequested = output();

  protected readonly options = computed<Option[]>(() => {
    const a = this.attention();
    return a.options
      .map((text, i) => ({text, firstLine: text.split('\n')[0], recommended: i === a.recommended}))
      .sort((x, y) => Number(y.recommended) - Number(x.recommended));
  });
  /** The session's default, offered only when it recommended none of its options. */
  protected readonly takeDefault = computed(() => {
    const a = this.attention();
    return a.default && a.recommended < 0 ? a.default : '';
  });
}

// console/src/components/AttentionCard.tsx
import { useState } from "react";
import { decideGoal, type Attention } from "../api";
import { relativeTime } from "../util/time";

// One goal's ask, rendered the same on the needs-you page and the goal page.
// Buttons exist only for a session block: they are the session's options,
// the recommended one first. A host-authored stop shows its fact, a free-text
// decide and cancel — never options the host made up.
export function AttentionCard({
  goalId, a, onDecided, onCancel,
}: {
  goalId: string; a: Attention; onDecided: () => Promise<void> | void; onCancel?: () => Promise<void> | void;
}) {
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const decide = async (t: string) => {
    if (!t.trim()) return;
    setBusy(true);
    setErr(null);
    try {
      await decideGoal(goalId, t.trim());
      setText("");
      await onDecided();
    } catch (e) {
      setErr(String(e));
    } finally {
      setBusy(false);
    }
  };

  const order = a.options.map((o, i) => ({ o, i })).sort((x, y) => (x.i === a.recommended ? -1 : y.i === a.recommended ? 1 : x.i - y.i));
  const showDefault = a.default && a.recommended < 0;

  if (a.answered) {
    return (
      <div>
        <div style={{ fontSize: 13, whiteSpace: "pre-wrap" }}>{a.question}</div>
        <div className="secondary" style={{ fontSize: 12.5, marginTop: 8 }}>
          Answered {relativeTime(a.answered.madeAt)}: <span style={{ color: "var(--text)" }}>{a.answered.text}</span>
          {a.answered.commentUrl && <> · <a href={a.answered.commentUrl} target="_blank" rel="noreferrer">thread</a></>}
        </div>
        <div className="mono muted" style={{ fontSize: 11.5, marginTop: 4 }}>waiting for the tick · {a.answered.waitingOn}</div>
      </div>
    );
  }

  return (
    <div>
      <div className="mono muted" style={{ fontSize: 11, marginBottom: 6 }}>
        {a.kind} · open {relativeTime(a.since)}
        {a.link && <> · <a href={a.link} target="_blank" rel="noreferrer">{a.kind === "session" || a.kind === "env" ? "issue" : "thread"}</a></>}
      </div>
      <div style={{ fontSize: 13, whiteSpace: "pre-wrap" }}>{a.question}</div>
      {a.kind === "env" && <p className="secondary" style={{ fontSize: 12.5, margin: "8px 0 0" }}>Wakes on its own once the credential probes green.</p>}
      {a.kind !== "env" && (
        <>
          {(order.length > 0 || showDefault) && (
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}>
              {order.map(({ o, i }) => (
                <button key={i} className={`btn sm${i === a.recommended ? " primary" : ""}`} disabled={busy} onClick={() => decide(o)} title={o}>
                  <span className="truncate" style={{ maxWidth: 360 }}>{o.split("\n")[0]}</span>
                  {i === a.recommended && <span className="mono" style={{ opacity: 0.75, fontSize: 10.5 }}>recommended</span>}
                </button>
              ))}
              {showDefault && (
                <button className="btn sm primary" disabled={busy} onClick={() => decide(a.default)} title={a.default}>
                  take the default: <span className="truncate" style={{ maxWidth: 320 }}>{a.default}</span>
                </button>
              )}
            </div>
          )}
          <div style={{ display: "flex", gap: 8, marginTop: 10 }}>
            <input className="input" style={{ flex: 1 }} value={text} onChange={(e) => setText(e.target.value)} disabled={busy}
              placeholder={order.length > 0 ? "or answer in your own words" : "your decision, posted on the issue"} />
            <button className="btn sm" onClick={() => decide(text)} disabled={busy || !text.trim()}>Decide</button>
            {onCancel && <button className="btn ghost sm" onClick={() => onCancel()} disabled={busy}>Cancel goal</button>}
          </div>
        </>
      )}
      {err && <div style={{ color: "var(--red)", fontSize: 12.5, marginTop: 8 }}>{err}</div>}
    </div>
  );
}
