// frontend/src/app/components/verdict-list.component.ts
import {ChangeDetectionStrategy, Component, input} from '@angular/core';
import {RouterLink} from '@angular/router';
import {DisclosureRowComponent, TagComponent, type TagVariant} from '@lifekit-hq/ui';

import {type VerdictRow} from '../api/devclaw.model';
import {ago} from '../shared/time';

const SHORT_SHA = 7;

export function verdictWord(v: VerdictRow): {text: string; variant: TagVariant} {
  if (v.unreadable) {
    return {text: 'unreadable', variant: 'warning'};
  }
  return v.achieved
    ? {text: 'achieved', variant: 'success'}
    : {text: 'not achieved', variant: 'error'};
}

/**
 * The done-gate's reviews, each expandable to clause by clause with the evidence verbatim. On
 * the verdicts page (across goals) and on the goal page (its own).
 */
@Component({
  selector: 'dc-verdict-list',
  imports: [DisclosureRowComponent, RouterLink, TagComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (v of rows(); track v.taskId) {
      @let word = verdictWord(v);
      <cmn-disclosure-row
        [label]="(v.unreadable ? v.rawError : v.summary) || word.text"
        [sublabel]="sublabel(v)"
        [open]="false"
      >
        <cmn-tag [variant]="word.variant" status>{{ word.text }}</cmn-tag>
        <div class="flex flex-col gap-cmn-2 px-cmn-4 pb-cmn-4 text-cmn-sm">
          @if (v.unreadable) {
            <p class="text-status-warning">
              The review produced no readable verdict{{ v.rawError ? ': ' + v.rawError : '' }}.
            </p>
          }
          @if (v.clauses.length) {
            <ul class="flex flex-col gap-cmn-2">
              @for (c of v.clauses; track $index) {
                @let met = c.satisfied && !!c.evidence;
                <li class="grid grid-cols-[1.25rem_minmax(0,1fr)] gap-cmn-2">
                  <span
                    [class]="met ? 'text-status-success' : 'text-status-error'"
                    class="font-mono"
                    >{{ met ? '✓' : '✗' }}</span
                  >
                  <span>
                    <span class="block text-text-primary">{{ c.clause }}</span>
                    <span
                      class="block whitespace-pre-wrap font-mono text-cmn-xs text-text-secondary"
                      >{{ c.evidence || 'no evidence' }}</span
                    >
                  </span>
                </li>
              }
            </ul>
          }
          @if (v.question) {
            <div>
              <h3 class="text-cmn-xs font-semibold text-text-secondary">Question for the owner</h3>
              <p class="text-text-primary">{{ v.question }}</p>
            </div>
          }
          @if (v.structuralHealth || v.concerns.length) {
            <div>
              <h3 class="text-cmn-xs font-semibold text-text-secondary">Structural health</h3>
              <p class="font-mono text-text-primary">{{ v.structuralHealth || '—' }}</p>
              @for (concern of v.concerns; track $index) {
                <p class="text-cmn-xs text-text-secondary">· {{ concern }}</p>
              }
            </div>
          }
          <p class="flex flex-wrap gap-cmn-3 font-mono text-cmn-xs">
            @if (showGoal() && v.goalId) {
              <a [routerLink]="['/goals', v.goalId]" class="text-accent-default hover:underline"
                >goal {{ v.goalId }}</a
              >
            }
            <a [routerLink]="['/sessions', v.taskId]" class="text-accent-default hover:underline"
              >review session</a
            >
            @if (v.prUrl) {
              <a
                [href]="v.prUrl"
                class="text-accent-default hover:underline"
                target="_blank"
                rel="noopener noreferrer"
                >the PR</a
              >
            }
          </p>
        </div>
      </cmn-disclosure-row>
    }
  `,
})
export class VerdictListComponent {
  public readonly rows = input.required<VerdictRow[]>();
  /** Across goals, each row names its goal. */
  public readonly showGoal = input(false);

  protected readonly verdictWord = verdictWord;

  protected sublabel(v: VerdictRow): string {
    const parts = [
      v.total > 0 ? `${v.satisfied}/${v.total} clauses` : '— clauses',
      v.head ? v.head.slice(0, SHORT_SHA) : '—',
      ago(v.completedAt ?? v.createdAt),
    ];
    return (this.showGoal() ? [v.goalId ?? '—', ...parts] : parts).join(' · ');
  }
}

// console/src/components/VerdictList.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { tokenQueryString, type VerdictRow } from "../api";
import { relativeTime } from "../util/time";

function word(v: VerdictRow): { text: string; color: string } {
  if (v.unreadable) return { text: "unreadable", color: "var(--amber)" };
  if (v.achieved) return { text: "achieved", color: "var(--green)" };
  return { text: "not achieved", color: "var(--red)" };
}

// The gate's rows, expandable to clause by clause with evidence verbatim.
// Used on the verdicts page (across goals) and on the goal page (its own).
export function VerdictList({ rows, showGoal }: { rows: VerdictRow[]; showGoal?: boolean }) {
  const qs = tokenQueryString();
  const [open, setOpen] = useState<Record<string, boolean>>({});
  const toggle = (id: string) => setOpen((o) => ({ ...o, [id]: !o[id] }));

  return (
    <div>
      {rows.map((v) => {
        const w = word(v);
        const isOpen = !!open[v.taskId];
        return (
          <div key={v.taskId} style={{ borderBottom: "1px solid var(--border)", padding: "10px 0" }}>
            <div className="rowlink" onClick={() => toggle(v.taskId)}
              style={{ display: "grid", gridTemplateColumns: `${showGoal ? "minmax(0,1.4fr) " : ""}110px 90px 80px minmax(0,1fr) 100px`, gap: 12, alignItems: "center", fontSize: 12.5 }}>
              {showGoal && (
                <span className="truncate">
                  {v.goalId ? <Link to={`/goals/${encodeURIComponent(v.goalId)}${qs}`} onClick={(e) => e.stopPropagation()}>{v.goalId}</Link> : "—"}
                </span>
              )}
              <span className="mono" style={{ color: w.color, fontWeight: 600 }}>{w.text}</span>
              <span className="mono secondary">{v.total > 0 ? `${v.satisfied}/${v.total}` : "—"}</span>
              <span className="mono muted">{v.head ? v.head.slice(0, 7) : "—"}</span>
              <span className="truncate secondary">{v.unreadable ? v.rawError : v.summary}</span>
              <span className="mono secondary" style={{ textAlign: "right" }}>{relativeTime(v.completedAt ?? v.createdAt)}</span>
            </div>
            {isOpen && (
              <div style={{ marginTop: 10, paddingLeft: 4, fontSize: 12.5 }}>
                {v.unreadable && <div style={{ color: "var(--amber)" }}>The review produced no readable verdict{v.rawError ? `: ${v.rawError}` : ""}.</div>}
                {v.clauses.map((c, i) => (
                  <div key={i} style={{ display: "grid", gridTemplateColumns: "18px minmax(0,1fr)", gap: 8, padding: "4px 0" }}>
                    <span className="mono" style={{ color: c.satisfied && c.evidence ? "var(--green)" : "var(--red)" }}>{c.satisfied && c.evidence ? "✓" : "✗"}</span>
                    <span>
                      <div>{c.clause}</div>
                      <div className="mono muted" style={{ fontSize: 11.5, whiteSpace: "pre-wrap" }}>{c.evidence || "no evidence"}</div>
                    </span>
                  </div>
                ))}
                {v.question && <div style={{ marginTop: 8 }}><span className="eyebrow">Question for the owner</span><div>{v.question}</div></div>}
                {(v.structuralHealth || v.concerns.length > 0) && (
                  <div style={{ marginTop: 8 }}>
                    <span className="eyebrow">Structural health</span>
                    <div className="mono">{v.structuralHealth || "—"}</div>
                    {v.concerns.map((c, i) => <div key={i} className="secondary" style={{ fontSize: 12 }}>· {c}</div>)}
                  </div>
                )}
                <div className="mono muted" style={{ fontSize: 11, marginTop: 8, display: "flex", gap: 10 }}>
                  <Link to={`/sessions/${encodeURIComponent(v.taskId)}${qs}`}>review session</Link>
                  {v.prUrl && <a href={v.prUrl} target="_blank" rel="noreferrer">the PR</a>}
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
